// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMbNUTc0wyM40SrwSi7a0oAW16I_fVXrg',
    appId: '1:145487681852:web:ccf5e5343d5ad79e6f6639',
    messagingSenderId: '145487681852',
    projectId: 'e-commerce-app-2d719',
    authDomain: 'e-commerce-app-2d719.firebaseapp.com',
    storageBucket: 'e-commerce-app-2d719.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBg8q99t0CErWT5BomR3DpA8npjDkZ9JtI',
    appId: '1:145487681852:android:b52f2d0c9ff50ee46f6639',
    messagingSenderId: '145487681852',
    projectId: 'e-commerce-app-2d719',
    storageBucket: 'e-commerce-app-2d719.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUsE0y-fGK7TkOm4xGOxYY2fxJK9dnsVg',
    appId: '1:145487681852:ios:ad92af67f139137d6f6639',
    messagingSenderId: '145487681852',
    projectId: 'e-commerce-app-2d719',
    storageBucket: 'e-commerce-app-2d719.appspot.com',
    androidClientId: '145487681852-u38snpcmp3enik298mcr9k4tb0g9pumb.apps.googleusercontent.com',
    iosClientId: '145487681852-lneh02t7emri0dq2p22vnj60ojl3cpkj.apps.googleusercontent.com',
    iosBundleId: 'com.example.tStore',
  );

}